# spring-boot-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-service-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: price-service-app
  template:
    metadata:
      labels:
        app: price-service-app
    spec:
      containers:
      - name: price-service-app
        image: price-service/price-service:latest
        ports:
        - containerPort: 8080  # Specify the port your Spring Boot app is listening on

---

apiVersion: v1
kind: Service
metadata:
  name: price-service
spec:
  selector:
    app: price-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Specify the port your Spring Boot app is listening on
  type: LoadBalancer  # Use 'LoadBalancer' if running in a cloud environment; use 'NodePort' or 'ClusterIP' for other environments
